version: "3"
services:
  keycloak-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  muisti-api-mysql:
    image: mysql:5.7
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muisti-api
      MYSQL_USER: muisti-api
      MYSQL_PASSWORD: password
  test-keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      JDBC_PARAMS: "verifyServerCertificate=false&useSSL=false"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/docker/kc.json
    ports:
      - 8080:8080
    depends_on:
      - keycloak-mysql
    volumes:
      - ./test-volumes/keycloak:/opt/docker
  muisti-api:
    build: .
    ports:
      - 1234:8080
    depends_on:
      - muisti-api-mysql
      - test-keycloak
    environment:
      API_HOST: localhost
      API_CLUSTER_PASSWORD: 4a0fc96f-c8d4-45c9-af69-4b7edd62df0d
      API_DB_HOST: muisti-api-mysql
      API_DB_NAME: muisti-api
      API_DB_USERNAME: muisti-api
      API_DB_PASSWORD: password
      KEYCLOAK_SECRET: a1d94fb9-0f35-42e8-a56a-001ffab13e6e
      KEYCLOAK_REALM: muisti
      KEYCLOAK_RESOURCE: api
      KEYCLOAK_URL: http://test-keycloak:8080/auth
      KUBERNETES_NAMESPACE: test
      FILE_STORAGE_PROVIDER: LOCAL
      LOCAL_FILE_STORAGE_PATH: /opt/uploads
      JAVA_OPTS: '-javaagent:/opt/jacoco-jacocoagent.jar=output=file,append=false,dumponexit=true,destfile=/opt/jacoco/it.exec'
    volumes:
      - ./test-volumes/uploads:/opt/uploads
      - $JACOCO_AGENT:/opt/jacoco-jacocoagent.jar
      - $JACOCO:/opt/jacoco