version: "3"
services:
  keycloak-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  muisti-api-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muisti-api
      MYSQL_USER: muisti-api
      MYSQL_PASSWORD: password
  keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JDBC_PARAMS: "verifyServerCertificate=false&useSSL=false"
      KEYCLOAK_IMPORT: /opt/docker/kc.json
    ports:
      - 8080:8080
    depends_on:
      - keycloak-mysql
    volumes:
      - ./test-volumes/keycloak:/opt/docker
  muisti-api:
    build: .
    ports:
      - 1234:8080
    depends_on:
      - muisti-api-mysql
    environment:
      API_HOST: localhost
      API_CLUSTER_PASSWORD: 4a0fc96f-c8d4-45c9-af69-4b7edd62df0d
      API_DB_HOST: muisti-api-mysql
      API_DB_NAME: muisti-api
      API_DB_USERNAME: root
      API_DB_PASSWORD: password
      KUBERNETES_NAMESPACE: test